### PR TITLE
Handle separator map and map target separately

### PR DESCRIPTION
**Pull request by bmundt6**
Fixes the error mentioned in #77. Still doesn't quite Tableize properly using a custom separator, but at least setting a custom separator no longer spits an error.

### CODE REVIEW

**Review by dhruvasagar — CHANGES_REQUESTED** [review]
* Need to update `doc/table-mode.txt`
* Need to fix specs, likely you just have to update `t/config/options.vim` and add the new global variables

**Comment by dhruvasagar** [comment]
@bmundt6 Are you going to complete this ?

**Comment by bmundt6** [comment]
Sure, I can do that!

**Review by dhruvasagar — APPROVED** [review]

**Comment by dhruvasagar** [comment]
@bmundt6 I have pushed the fixes, kindly review and mark the PR as ready so we can merge. Thanks for your time.

**Comment by bmundt6** [comment]
Thanks @dhruvasagar the doc is good! My apologies for not getting to this sooner!

**Review by dhruvasagar — APPROVED** [review]

**Pull request merged**
