### PR TITLE
feat(highlight): color cell if contains yes,no,?

### PR DESCRIPTION
**Pull request by jdorel**
image

### CODE REVIEW

**Comment by jdorel** [comment]
Made a little mistake with the regex : currently fixing it

**Comment by dhruvasagar** [comment]
Thanks, not particularly needed, but still a nice touch.

**Comment by jdorel** [comment]
I was just thinking about it, and maybe a more modular approach could also be useful ? Something like a prefix to define the color :
image
Should I do a PR like this ?

**Comment by Saroth** [comment]
> 

I am sorry this PR cause my NVim very slow when I enable the Table Mode in a markdown file. The .md file has about 20 tables.
I revert the commit 0fe6bd8, and now works well.
This PR may improve performance, I will try later...  :)

**Pull request merged**
