### PR TITLE
Add a way to insert columns

### LINKED ISSUE #130: Command to insert a new column
Creating a new column manually in an existing table is doable annoying. Would be nice to have "insert column left/right of cursor" commands.

### PR DESCRIPTION
**Pull request by ibbem**
This closes #130 by providing a way to add a column before and after the current column.

This also fixes a bug when deleting columns: If a table had an header it wouldn't have been updated.

I have included tests for tables with headers using different fill chars and alignment characters, because these where tricky to spot when implementing.

I'm fairly new to contributing to open source, so please feel free to tell me if I'm doing something wrong.

### CODE REVIEW

**Comment by ibbem** [comment]
I fixed two more bugs which affect inserting columns as well as deleting columns.

**Comment by ibbem** [comment]
I discovered the g:table_mode_escaped_separator_regex and incorporated it into the code.

**Comment by dhruvasagar** [comment]
@ibbem Let me know your thoughts

**Comment by ibbem** [comment]
Yes this works very well. I just added it.

**Pull request merged**
